name = "cf-ts-router-template"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-02-20"

[build]
command = "webpack"
[build.upload]
format = "service-worker"
